# Generated by Django 3.2.12 on 2024-05-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='Default College Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=50),
        ),
    ]
