# Generated by Django 3.2.12 on 2024-05-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20240531_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=255),
        ),
    ]
